/* Shared navigation, footer, search, counters and interface behavior */
const page=document.body.dataset.page||'';
const links=[['Home','index.html','home'],['About','about.html','about'],['Services','services.html','services'],['Portfolio','portfolio.html','portfolio'],['Pricing','pricing.html','pricing'],['Blog','blog.html','blog'],['Contact','contact.html','contact']];
document.querySelector('#site-header').innerHTML=`<a class="visually-hidden-focusable" href="#main">Skip to content</a><nav class="navbar navbar-expand-lg fixed-top"><div class="container"><a class="navbar-brand" href="index.html">MQAMTECH<span class="brand-dot">.</span></a><button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#nav"><i class="fa-solid fa-bars"></i></button><div class="collapse navbar-collapse" id="nav"><ul class="navbar-nav ms-auto align-items-lg-center">${links.map(([n,u,k])=>`<li class="nav-item"><a class="nav-link ${page===k?'active':''}" href="${u}">${n}</a></li>`).join('')}<li class="nav-item dropdown"><a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">More</a><ul class="dropdown-menu border-0 shadow"><li><a class="dropdown-item" href="faq.html">FAQ</a></li><li><a class="dropdown-item" href="careers.html">Careers</a></li></ul></li></ul><button class="theme-toggle" aria-label="Toggle dark mode"><i class="fa-solid fa-moon"></i></button><button class="theme-toggle search-toggle" aria-label="Search site"><i class="fa-solid fa-magnifying-glass"></i></button></div></div></nav><div class="search-panel" aria-hidden="true"><form class="search-box d-flex align-items-center" action="services.html"><input class="form-control" type="search" name="q" placeholder="Search our services..." aria-label="Search"><button class="search-close" type="button" aria-label="Close search">×</button></form></div>`;
document.querySelector('#site-footer').innerHTML=`<footer class="site-footer"><div class="container"><div class="row g-4"><div class="col-lg-4"><a class="footer-brand" href="index.html">MQAMTECH<span class="brand-dot">.</span></a><p class="mt-3 pe-lg-5">Practical, secure technology solutions for ambitious organisations in Oujda, Morocco and beyond.</p><div class="social"><a href="https://www.linkedin.com" aria-label="LinkedIn"><i class="fa-brands fa-linkedin-in"></i></a><a href="https://www.facebook.com" aria-label="Facebook"><i class="fa-brands fa-facebook-f"></i></a><a href="https://wa.me/212691999014" aria-label="WhatsApp"><i class="fa-brands fa-whatsapp"></i></a></div></div><div class="col-6 col-lg-2"><h3>Company</h3><ul><li><a href="about.html">About us</a></li><li><a href="portfolio.html">Our work</a></li><li><a href="blog.html">Insights</a></li><li><a href="careers.html">Careers</a></li></ul></div><div class="col-6 col-lg-2"><h3>Services</h3><ul><li><a href="services.html">IT support</a></li><li><a href="services.html#security">Cybersecurity</a></li><li><a href="services.html#development">Development</a></li><li><a href="services.html#cloud">Cloud solutions</a></li></ul></div><div class="col-lg-4"><h3>Stay informed</h3><p>Practical technology insights, delivered occasionally.</p><form class="newsletter d-flex gap-2"><input class="form-control" type="email" placeholder="Your email address" aria-label="Email address" required><button class="btn btn-primary" type="submit">Join</button></form></div></div><div class="footer-bottom d-flex flex-wrap justify-content-between gap-2"><span>© ${new Date().getFullYear()} MQAMTECH. All rights reserved.</span><span><a href="privacy.html">Privacy Policy</a> &nbsp;·&nbsp; <a href="terms.html">Terms of Service</a></span></div></div></footer>`;
document.querySelectorAll('.newsletter').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const b=f.querySelector('button');b.textContent='Thank you!';f.reset()}));
document.querySelector('.search-toggle').onclick=()=>document.querySelector('.search-panel').classList.add('open');document.querySelector('.search-close').onclick=()=>document.querySelector('.search-panel').classList.remove('open');
const top=document.querySelector('.back-top');window.addEventListener('scroll',()=>top.classList.toggle('show',scrollY>400));top.onclick=e=>{e.preventDefault();scrollTo({top:0,behavior:'smooth'})};
const counterObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(!e.isIntersecting)return;const el=e.target,end=+el.dataset.counter;let n=0;const tick=()=>{n=Math.min(end,n+Math.ceil(end/45));el.textContent=n+(end===50?'+':end===99?'%':'+');if(n<end)requestAnimationFrame(tick)};tick();counterObserver.unobserve(el)}),{threshold:.6});document.querySelectorAll('[data-counter]').forEach(e=>counterObserver.observe(e));
document.querySelectorAll('.portfolio-filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.portfolio-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.portfolio-item').forEach(i=>i.classList.toggle('hide',b.dataset.filter!=='all'&&i.dataset.category!==b.dataset.filter))});
